version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: sidekick
    container_name: sidekick-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - sidekick

networks:
  sidekick:
    driver: bridge
